# d={"brand":"mast","mango":"apple","kanchan":"patota","aata":"gehu"}
# i=0
# while i <len(d):
#     print(i)
#     i=i+1
    # IT IS PRINTING INDEX




# d={"brand":"mast","mango":"apple","kanchan":"patota","aata":"gehu"}
# for i ,k in d.items():
#     print(i,k)
    # IT WILL PRINT KEY VALUE



# d={"brand":"mast","mango":"apple","kanchan":"patota","aata":"gehu"}
# for i,y in d.items():
#     print(i,"  ",y)
#  IT WILL PRINT KEY AND VALUE BOTH


# d={"name":"shanti","place":"uttar pradesh","village":"my home"}
# d["place"]="banglore"
# print(d)
# CHANGEING VALUE



# d={"brand":"mast","mango":"apple","kanchan":"patota","aata":"gehu"}
# for i in d:
#     print(i)
# It will print KEY 



# d={'brand':"madel","patao":'name',"panu":"mznb"}
# for i in d.values():
#     print(i)
#  IT WILL PRINT VALUE


# print(2**3%(4-1/2)*2+1) 
# print(3.5*2)
# print(8%7)
# print(4%2**3*4)






# a="Sh@nti"
# i=1
# while i<=len(a):
    
#     print(a[-i])
#     i+=1
# It will print oupsit...





# a="my name is shanti"
# i=0
# while i<len(a):
#     if a[i]==" ":
#         pass 
#     else:
#         print(a[i],end=" ")
#     i=i+1
# It will print space....



# a="my name is shanti"
# i=0
# while i<len(a):
#     if a[i]==" ":
#         pass 
#     else:
#         print(a[i],end="")
#     i=i+1dict

# +++++++++++O/P+++++++++++++

# {'id2': {'subject_integration': ['english, math, science'], 'class': ['V'], 'name': ['David']}, 'id4': {'subje
# ct_integration': ['english, math, science'], 'class': ['V'], 'name': ['Surya']}, 'id1': {'subject_integration'
# : ['english, math, science'], 'class': ['V'], 'name': ['Sara']}} 


student_data = {'id1': 
   {'name': ['Sara'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
   },
 'id2': 
  {'name': ['David'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
   },
 'id3': 
    {'name': ['Sara'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
   },
 'id4': 
   {'name': ['Surya'], 
    'class': ['V'], 
    'subject_integration': ['english, math, science']
   },
}





